AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-user-checkin

  Sample SAM Template for sam-user-checkin

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Tags:
      Environment: !Ref Environment
      Name: SpacesAI-Checkin
    Timeout: 3
    MemorySize: 128
Parameters:
  Environment:
    Type: String
    Description: SpacesAI
    Default: dev

Resources:
  UserCheckinTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
  UserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/Functions/UserServices/
      Handler: index.lambdaHandler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Events:
        Checkin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /checkin/{id}
            Method: get
      Environment:
        Variables:
          # USER_CHECKIN_CONNECTION_TABLE_NAME: !Ref UserCheckinTableName
          USER_CHECKIN_TABLE: !Ref UserCheckinTable
          USER_CHECKIN_TABLE_ARN: !GetAtt UserCheckinTable.Arn
      Policies:
        # - DynamoDBCrudPolicy:
        #     TableName: !Ref UserCheckinTableName
        - DynamoDBCrudPolicy:
            TableName: !Ref UserCheckinTable

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UserFunctionApi:
    Description: 'API Gateway endpoint URL for Prod stage for Hello World function'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/checkin/'
  UserFunction:
    Description: 'Hello World Lambda Function ARN'
    Value: !GetAtt UserFunction.Arn
  UserFunctionIamRole:
    Description: 'Implicit IAM Role created for Hello World function'
    Value: !GetAtt UserFunctionRole.Arn
